### ISSUE TITLE
Syntax error in deploy.py

### ISSUE THREAD

**Issue by mcfriend99** [iGhibli/iOS-DeviceSupport#117]
Did a fresh clone and tried to run. Here is my result:

```
MacBook-Pro:iOS-DeviceSupport username$ sudo ./deploy.py
Password:
  File "./deploy.py", line 25
    print 'Unzip file "{}.zip" to {}'.format(i, target)
          ^
SyntaxError: invalid syntax
```

How are we supposed to get this thing running??

**Comment by Merculous** [comment]
Your python version is probably 3.x. The code is made from python 2.x so, you should be running any 2.x version of python.

**Comment by mcfriend99** [comment]
I noticed that already and I have already updated the code. Thanks for the contribution.
