### ISSUE TITLE
Version 16A5327f is beta 4 so why you say 16A5327d ?

### ISSUE THREAD

**Issue by softlion** [iGhibli/iOS-DeviceSupport#12]

**Comment by iGhibli** [comment]
Sorry, This name may be wrong. These support files(16A5327d) are included in the latest version of Xcode(Xcode_10_beta_4). So I call it beta 4. Thank you for correcting my mistake.

**Comment by softlion** [comment]
Hi,
i'm sure for the version number. See also https://ipsw.me/otas/iPhone10,6

I installed xcode 10 beta and grabbed them manually after the phone is connected.

**Comment by softlion** [comment]
16A5327d is the previous version.

**Comment by softlion** [comment]
I suppose they make a difference between public beta and "private" beta ?
