### ISSUE TITLE
I want iOS 12.0 (16A5362a)

### ISSUE THREAD

**Issue by anjingpan** [iGhibli/iOS-DeviceSupport#16]

**Comment by jefflnorton** [comment]
Need 16A5364a please.

**Comment by Positivism** [comment]
16A5364a Bump

**Comment by iGhibli** [comment]
The latest beta Xcode I can download from the Apple Developer Download Center(`https://developer.apple.com/download/`) is Xcode 10 beta 6.
The latest support files
included with Xcode 10 beta 6 is iOS 12.0 (`16A5354b`).
So I'm sorry, I don't know where to download the support files(`16A5362a`/`16A5364a`) you need. If you know the download link, please tell me. Thank you!

**Comment by Positivism** [comment]
Perhaps support files are only included by apple for the public beta.
