### ISSUE TITLE
Please add iOS 12 Beta 12 support files - 16A5366a

### ISSUE THREAD

**Issue by rahulgolwalkar-one** [iGhibli/iOS-DeviceSupport#17]

**Comment by iGhibli** [comment]
The latest beta Xcode I can download from the Apple Developer Download Center(`https://developer.apple.com/download/`) is Xcode 10 beta 6. The latest support files
included with Xcode 10 beta 6 is iOS 12.0 (`16A5354b`). So I'm sorry, I don't know where to download the support files(`16A5366a`) you need. If you know the download link, please tell me. Thank you!

**Comment by Agenric** [comment]
Now the latest version is iOS 12.1(`16B5069d`)，can you add support for this version?

**Comment by Agenric** [comment]
thx @iGhibli
