### ISSUE TITLE
Please add iOS 15.1 from new Xcode 13.1(13A1030d)

### ISSUE THREAD

**Issue by UnivexDont** [iGhibli/iOS-DeviceSupport#170]
Please add iOS 15.1 from new Xcode 13.1(13A1030d)

**Comment by iMazy** [comment]
Go into contents/Developer/platform/iPhoneOS.platform/DeviceSupport
Copy your previous iOS 14.5 the device support file or older version
Paste into the same folder and change the iOS number to 14.6
Restart Xcode, and it should let you run your code on your phone
