### ISSUE TITLE
Where is fu*king iOS 15.1 Support Device

### ISSUE THREAD

**Issue by UnivexDont** [iGhibli/iOS-DeviceSupport#171]

**Comment by fatzhou** [comment]
Help help help

**Comment by iMazy** [comment]
Go into contents/Developer/platform/iPhoneOS.platform/DeviceSupport
Copy your previous iOS 14.5 the device support file or older version
Paste into the same folder and change the iOS number to 14.6
Restart Xcode, and it should let you run your code on your phone

**Comment by yangyu2010** [comment]
try this
https://github.com/filsv/iPhoneOSDeviceSupport/blob/98faafe53a59d3e8d1c22ab15a34a799d4b96e1b/15.1%20(19B74).zip

**Comment by DaviGn** [comment]
Not working on iPhone X iOS 15.1

**Comment by yangyu2010** [comment]
@DaviGn my device is iPhone XS, its works. and you can try this https://github.com/filsv/iPhoneOSDeviceSupport
