### ISSUE TITLE
Hello, Is there for 15.6?

### ISSUE THREAD

**Issue by Erchil66** [iGhibli/iOS-DeviceSupport#183]

**Comment by adVenturesIncBnB** [comment]
Have you got it

**Comment by mcjambi** [comment]
i am waiting here with you!

**Comment by otaviokz** [comment]
👀

**Comment by ismailozsaygi** [comment]
Agreed, waiting for 15.6. Can't use devices for test that has 15.6 installed atm.

**Comment by CagkanCaglayanelPT** [comment]
I am waiting for this too 👀

**Comment by Mukthayar1** [comment]
@NoeOnJupiter please give update on ios 15.6 .
thanks

**Comment by sup8369** [comment]
https://github.com/iGhibli/iOS-DeviceSupport/pull/186

**Comment by SaeedRahmatolahi** [comment]
you can use it Guys

**Comment by jordanZeleny** [comment]
@SaeedRahmatolahi How? I've been trying for hours.

**Comment by SaeedRahmatolahi** [comment]
you need to force close and open the Xcode again then you will be able to run it

**Comment by jordanZeleny** [comment]
which iOS support file are you using? and what Xcode version?

**Comment by SaeedRahmatolahi** [comment]
Xcode 13.3.1

**Comment by sunmean** [comment]
https://github.com/sunmean/iOS-DeviceSupport

**Comment by kaverlin** [comment]
> #186

Thanks for the link !
