### ISSUE TITLE
Could you add 12.1.1 (16C50)?

### ISSUE THREAD

**Issue by GelarAulia** [iGhibli/iOS-DeviceSupport#24]
I know it's still fresh and new. It is really new, like, updated on 5 December 2018. But now I couldn't run app to my phone cause I'm using Xcode 10 and I thought I was updating my device to 12.1 instead of 12.1.1. Thank you.

**Comment by madakopihub** [comment]
Yeah,, i need this version too,, please

**Comment by iGhibli** [comment]
Sorry, I can't find the download link for the `12.1.1 (16C50)` support file.

The latest version of Xcode is still `Xcode 10.1` on the [Apple Developer website ](https://developer.apple.com/download/).

Then I tried to update my iPhone to the latest version `(iOS 12.1.1)`. The latest iOS version (`iOS 12.1.1`) can still debug & run with `Xcode10.1` (`12.1 (16B91)`).

**Comment by GelarAulia** [comment]
@iGhibli Well, I actually I've tried download your 16B91 and use it with Xcode 10 but it doesn't work with iOS 12.1.1. I ended up downgrading my iOS to 12.1 and use your 16B91. 

After a while I got time to download Xcode 10.1 from Apple Developer website. But I haven't tested it on 12.1.1. Is there a difference between Xcode from Apple Developer website and Xcode from App Store?
