### ISSUE TITLE
Localizable Strings

### ISSUE THREAD

**Issue by Kaleem-b-bigstep** [iGhibli/iOS-DeviceSupport#25]
"Add" = "Add";

"Add Friends to see new\nupdates and keep up with\nlatest news." = "Add Friends to see new\nupdates and keep up with\nlatest news.";

"No Listings available at this moment, be the first one to create" = "No Listings available at this moment, be the first one to create";

"No Listings available at this moment" = "No Listings available at this moment";

"No updates at this moment . Check again any other time." = "No updates at this moment . Check again any other time.";

"Try Again" = "Try Again";

**Comment by iGhibli** [comment]
**What**❓❓❓
