### ISSUE TITLE
Please Add WatchOS support files - (16S46)

### ISSUE THREAD

**Issue by Riwak** [iGhibli/iOS-DeviceSupport#27]
Hi and thank you for providing support files. please add latest version of support files after update for new ones as we can not develop and check our apps on new versions.

**Comment by iGhibli** [comment]
I have uploaded the **watchOS support files** in another newly created [repository](https://github.com/iGhibli/watchOS-DeviceSupport).

It contains [the latest version support files](https://github.com/iGhibli/watchOS-DeviceSupport/tree/master/DeviceSupport/5.1%20(16R591))(`From Xcode_10.1 (10B61)`) what I can find.

Hope it's helpful to you.
