### ISSUE TITLE
please add IOS12.2 (16E227)，thanks very much

### ISSUE THREAD

**Issue by LixingY** [iGhibli/iOS-DeviceSupport#37]

**Comment by patiljignesh** [comment]
I am also looking for this. Have you managed to get the files? @LixingY

**Comment by LixingY** [comment]
> I am also looking for this. Have you managed to get the files? @LixingY

I am also looking for this

**Comment by dinarajas** [comment]
Wouldn't this work? https://github.com/iGhibli/iOS-DeviceSupport/pull/36

**Comment by LixingY** [comment]
> Wouldn't this work? #36

I downloaded this file ，but could not download it，Can you send a copy to my mailbox?

**Comment by dinarajas** [comment]
> > Wouldn't this work? #36
> 
> I downloaded this file ，but could not download it，Can you send a copy to my mailbox?

Check out this in my fork and download!
https://github.com/dinarajas/iOS-DeviceSupport/blob/ios12-2/DeviceSupport/12.2%20(16E226).zip

**Comment by LixingY** [comment]
> > > Wouldn't this work? #36
> > 
> > 
> > I downloaded this file ，but could not download it，Can you send a copy to my mailbox?
> 
> Check out this in my fork and download!
> https://github.com/dinarajas/iOS-DeviceSupport/blob/ios12-2/DeviceSupport/12.2%20(16E226).zip

Wow, thank you very much！！

**Comment by LixingY** [comment]
> I am also looking for this. Have you managed to get the files? @LixingY

Try this #36

**Comment by patiljignesh** [comment]
Thank you so much @dinarajas

**Comment by iGhibli** [comment]
iOS 12.2(16E226) support files is already uploaded. (From Xcode_10.2) 

Thank you so much! @dinarajas
