### ISSUE TITLE
Please add iOS 12.2 (16E227) support files

### ISSUE THREAD

**Issue by sarathvad1811** [iGhibli/iOS-DeviceSupport#38]
Hi and thank you for providing support files. please add latest version of support files after update for new ones as we can not develop and check our apps on new versions.
i'm using a an old MAC MINI on which I can't update my OS version to Mojave and hence cannot update to Xcode. all i can do is to download support files and this repo is my only hope
thanks.

**Comment by leeguooooo** [comment]
i need, too...

**Comment by igorpwnd** [comment]
please, upload 16E277 support files as soon you can. 

Thanks!

**Comment by gams95** [comment]
I ran my app through xcode on my iPhone 7 running 16E227 with the 16E226 support file and it works

**Comment by sarathvad1811** [comment]
Yes 16E226 is working :)

**Comment by tail-call** [comment]
Thanks a lot! Works like a charm.

**Comment by maninp** [comment]
See this StackOverflow question to use 16E226 for 16E227. https://stackoverflow.com/questions/55575782/xcode-missing-support-files-ios-12-2-16e227
