### ISSUE TITLE
Please add 12.4 (16G77)

### ISSUE THREAD

**Issue by JideGuru** [iGhibli/iOS-DeviceSupport#51]

**Comment by CarolinaStephanie** [comment]
Please...

**Comment by Shan7anu** [comment]
**Please add Device Support for iOS 12.4 (16G77)**

**Comment by davideickhoff** [comment]
I have just renamed 16G73 in 16G77 and it worked for now ;)

**Comment by Shan7anu** [comment]
Thanks @davideickhoff ! :)

**Comment by mldoscar** [comment]
> I have just renamed 16G73 in 16G77 and it worked for now ;)

Worked for me on iPhone 7 Plus with iOS 12.4 (16G77) and Xcode Version 10.1 (10B61)

**Comment by JideGuru** [comment]
Renaming 16G73 to 16G77 solves the issue for now.
