### ISSUE TITLE
can you add devicesupport for ios 13.1.

### ISSUE THREAD

**Issue by Frankenstein666** [iGhibli/iOS-DeviceSupport#54]

**Comment by eskerber** [comment]
Device support for 13.1 does not exist in any Xcode beta yet.

**Comment by msmollin** [comment]
Support was added in Xcode 11b7
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_7_release_notes

**Comment by Frankenstein666** [comment]
seems like you have to download latest beta of xCode 11 (beta 7 ) to be able to run apps on iOS 13.1 devices. I opened up the package contents of beta 7 and cannot find device support for iOS 13.1.
