### ISSUE TITLE
iOS 13.2 (17B5059g) device Support files

### ISSUE THREAD

**Issue by divyansh-iimjobs** [iGhibli/iOS-DeviceSupport#65]
Hi, 
It would be a great help if you can please add **iOS 13.2 (17B5059g)** device Support files. I am unable to find the same anywhere.

**Comment by truongduy997** [comment]
me too, please help me because i did upgraded to **iOS 13.2 (17B5059g)**

**Comment by emreisik95** [comment]
Me too, please keep me informed.

**Comment by emreisik95** [comment]
> Hi,
> It would be a great help if you can please add **iOS 13.2 (17B5059g)** device Support files. I am unable to find the same anywhere.



> me too, please help me because i did upgraded to **iOS 13.2 (17B5059g)**

https://github.com/Yatko/iOS-device-support-files/tree/master/13.2%20(17B5059f)

If you'll need it immediately, you can use this repo.

**Comment by truongduy997** [comment]
Thank u @emreisik95, it worked for me 😀😀😀

**Comment by divyansh-iimjobs** [comment]
Thank you @emreisik95, i got it from Xcode 11.2 beta, but it is also of great help.  :)
