### ISSUE TITLE
Please add iOS 13.2 (17B84) support files for Xcode 11

### ISSUE THREAD

**Issue by akazadd** [iGhibli/iOS-DeviceSupport#75]

**Comment by liuyx7894** [comment]
I have same problem, please add 13.2 (17B84) thx.

**Comment by shibin919** [comment]
Same issue , please add 13.2 (17B84) , Thanks in advns.

**Comment by bystritskiy** [comment]
Same issue

**Comment by Fouda** [comment]
the existing device support 13.2 will encountering this error:  yld_shared_cache_extract_dylibs failed

Please update it with the one from the released Xcode 11.2.1_GM_Seed.

**Comment by aissat** [comment]
Same issue

**Comment by andoma93** [comment]
> the existing device support 13.2 will encounter this error: yld_shared_cache_extract_dylibs failed
> 
> Please update it with the one from the released Xcode 11.2.1_GM_Seed.

Same error with Xcode 11.2.1_GM_Seed support files.

**Comment by Fouda** [comment]
@andoma93  I have used the device support folder from Xcode 11.2.1_GM_Seed instead and it works fine for me. 

 here is the folder:  [13.2.zip](https://github.com/iGhibli/iOS-DeviceSupport/files/3831027/13.2.zip)


> > the existing device support 13.2 will encounter this error: yld_shared_cache_extract_dylibs failed
> > Please update it with the one from the released Xcode 11.2.1_GM_Seed.
> 
> Same error with Xcode 11.2.1_GM_Seed support files.

**Comment by andoma93** [comment]
> @andoma93 I have used the device support folder from Xcode 11.2.1_GM_Seed instead and it works fine for me.
> 
> here is the folder: [13.2.zip](https://github.com/iGhibli/iOS-DeviceSupport/files/3831027/13.2.zip)
> 
> > > the existing device support 13.2 will encounter this error: yld_shared_cache_extract_dylibs failed
> > > Please update it with the one from the released Xcode 11.2.1_GM_Seed.
> > 
> > 
> > Same error with Xcode 11.2.1_GM_Seed support files.

Unfortunately for me it doesn't work with the ones you uploaded (Thanks for that)

**Comment by andoma93** [comment]
Thanks @Fouda . After restarting xCode and upairing and pairing the device it works. I'll procede asking for a PR with the zip you uploaded. Thanks you!

**Comment by andoma93** [comment]
Created pull request #78 . Waiting for approval

**Comment by Fouda** [comment]
@andoma93  you are welcome.

**Comment by sunmean** [comment]
here is [13.2 ](https://github.com/sunmean/iOS-DeviceSupport)
