### ISSUE TITLE
 iOS 13.3 (17C5032d)

### ISSUE THREAD

**Issue by iT-Boyer** [iGhibli/iOS-DeviceSupport#76]
This iPad (5th generation) is running iOS 13.3 (17C5032d), which may not be supported by this version of Xcode.

**Comment by sser-huangdong** [comment]
I'm using a 7Plus running iOS 13.3 (17C5032d) and Xcode 10.2.1 to debug. I find out that Xcode 11.3 beta doesn't have 13.3 deviceSupport file. And after I just rename the 13.2 dictionary to 13.3, I can debug my code with my 7Plus.

**Comment by klemensz** [comment]
@sser-huangdong Nice, that did the trick!

**Comment by sourabhdadapure** [comment]
@sser-huangdong that works! amazing!

**Comment by sunmean** [comment]
This is[ iOS13.3 support files](https://github.com/sunmean/iOS-DeviceSupport/raw/master/13.3.zip)

**Comment by luthviar** [comment]
> This is[ iOS13.3 support files](https://github.com/sunmean/iOS-DeviceSupport/raw/master/13.3.zip)

is it working?
