### ISSUE TITLE
Please add iOS 13.3.1 

### ISSUE THREAD

**Issue by marloncepeda** [iGhibli/iOS-DeviceSupport#88]
Please add iOS 13.3.1

**Comment by Fatehkhann** [comment]
Please add iOS 13.3.1. Can't get my apps work with just 13.3

**Comment by bave233** [comment]
Please add iOS 13.3.1.

**Comment by sqzbx** [comment]
Download the 13.3 (17C54).zip support file. Copy and paste the folder to the DeviceSupport folder of xcode and rename it to be just "13.3", restart xcode and it should work.

That worked for me, hopefully it works for you guys too.
