### ISSUE TITLE
Add a script to put support file into Xcode.app?

### ISSUE THREAD

**Issue by xcv58** [iGhibli/iOS-DeviceSupport#9]
I can write a simple bash script to unzip the new support files and copy it into Xcode.app.
It will:
* Check what zip files are new
* Unzip the files and copy the folder to Xcode.app
* Able to set Xcode.app path for Xcode-beta.app

Would you like to accept such PR @iGhibli ?

**Comment by iGhibli** [comment]
Yes, Please. This makes it easier for everyone to use these support files. Thank you very much for doing this.
