### ISSUE TITLE
Please add iOS 13.4.5 (17F5044d)

### ISSUE THREAD

**Issue by huobazi** [iGhibli/iOS-DeviceSupport#98]
**Could not locate device support files.**

```
This iPhone 6s is running iOS 13.4.5 (17F5044d), which may not be supported by this version of Xcode. An updated version of Xcode may be found on the App Store or at developer.apple.com.

```

**Comment by winstondu** [comment]
@huobazi 

You can see my fork here: https://github.com/winstondu/iOS-latest-device-support

This will have the latest files.

**Comment by huobazi** [comment]
@winstondu 
tanks for help.
your repo work fine for me.
